---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: floating-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - ${FLOATING_IP}/32

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: floating-ip-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - floating-ip-pool